# Generated by Django 5.1.4 on 2025-01-03 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="city",
        ),
        migrations.AddField(
            model_name="station",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
