# Generated by Django 5.1.4 on 2025-01-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("train_service", "0002_remove_station_city_station_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="station",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
