# Generated by Django 5.1.4 on 2025-01-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "train_service",
            "0003_alter_station_latitude_alter_station_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="arrival_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="trip",
            name="departure_time",
            field=models.DateTimeField(),
        ),
    ]
